// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG49sPc2w3V_GJE1_AUhAUxP0jVToqzGM',
    appId: '1:651463480377:web:8358368b0bd5bd384be9e8',
    messagingSenderId: '651463480377',
    projectId: 'live-edu-6176f',
    authDomain: 'live-edu-6176f.firebaseapp.com',
    storageBucket: 'live-edu-6176f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPguFwPU_15hIV8zMPAT6D2eDY3eY4fwI',
    appId: '1:651463480377:android:ad0d3614177568714be9e8',
    messagingSenderId: '651463480377',
    projectId: 'live-edu-6176f',
    storageBucket: 'live-edu-6176f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrVu17PijQZBQ36f4YAwus8xsNLy-pDuM',
    appId: '1:651463480377:ios:a508f38a396a0a0f4be9e8',
    messagingSenderId: '651463480377',
    projectId: 'live-edu-6176f',
    storageBucket: 'live-edu-6176f.appspot.com',
    iosClientId: '651463480377-ugkko9o0vnccativ3lc8902utgtn3s4p.apps.googleusercontent.com',
    iosBundleId: 'com.example.liveEdu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrVu17PijQZBQ36f4YAwus8xsNLy-pDuM',
    appId: '1:651463480377:ios:a508f38a396a0a0f4be9e8',
    messagingSenderId: '651463480377',
    projectId: 'live-edu-6176f',
    storageBucket: 'live-edu-6176f.appspot.com',
    iosClientId: '651463480377-ugkko9o0vnccativ3lc8902utgtn3s4p.apps.googleusercontent.com',
    iosBundleId: 'com.example.liveEdu',
  );
}
